version: '3'

services: 
  api: 
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
      - HOST=https://realworld-docker.com
